### ISSUE TITLE
User login/auth

### ISSUE THREAD

**Issue by rocapal** [mwsrp/whos-that-whaleshark-android#2]
Some screenshots of the application workflow show that the user can 'like' the shark encounters and even they can check the list of the shark encounters they liked in the past. Is there any API to login the users? Or the idea could be save this information locally on the smartphone? (at least as a first step).

**Comment by yogaraptor** [comment]
Nope, not in the current API - this is something we'll develop. So yes, save locally for now.

**Comment by rocapal** [comment]
Perfect!
